site:
  name: BigBigDou
  site: 'https://bigbigdou.pages.dev'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

# Default SEO metadata
metadata:
  title:
    default: BigBigDou
    template: '%s — BigBigDou'
  description: '只有技术是不够的，这里有各种计算技术包括编程、AI人工智能、Web3、区块链、元宇宙、数据要素、还有科学实验、生活记录、有趣的手工聚集地，Aldis & Camila & Seven 联合出品'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: BigBigDou
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@Hello_Aldis'
    site: '@Hello_Aldis'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    postsPerPage: 6

    post:
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: true

    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'dark' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
